rules:
  - id: no-hardcoded-secrets
    patterns:
      - pattern-either:
          - pattern: "JWT_SECRET\s*=\s*['\"]$X$['\"]"
          - pattern: "OPENAI_API_KEY\s*=\s*['\"]$X$['\"]"
    message: "Hardcoded secret detected"
    languages: [python]
    severity: ERROR

  - id: no-eval
    pattern: eval(...)
    message: "Avoid eval()"
    languages: [python]
    severity: WARNING


