version: "3.9"
services:
  backend:
    build: ./backend
    container_name: forge-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://forge:forge@postgres:5432/forge
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_CORS_ORIGINS=*
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: ankane/pgvector:latest
    container_name: forge-postgres
    environment:
      - POSTGRES_USER=forge
      - POSTGRES_PASSWORD=forge
      - POSTGRES_DB=forge
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forge"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: forge-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata:


