name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Build
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            npm run build:production
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            npm run build:staging
          else
            npm run build
          fi
        env:
          NODE_ENV: production

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          output_location: ".next" # Built app content directory
          skip_app_build: true # Skip the build step, we already built
          deployment_environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

  # Optional: Add a comment to the PR with the preview URL
  comment_pr:
    runs-on: ubuntu-latest
    name: Comment PR
    if: github.event_name == 'pull_request'
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: deployments } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              branch: context.payload.pull_request.head.ref,
            });
            
            const deployment = deployments.workflow_runs.find(run => run.status === 'completed' && run.conclusion === 'success');
            
            if (deployment) {
              const { data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: deployment.id,
              });
              
              const comment = `🚀 **Preview Deployment Ready!**
              
              Your changes have been deployed to a preview environment.
              
              **Preview URL**: [View Preview](https://your-app-name.azurestaticapps.net)
              
              **Deployment Status**: ✅ Success
              **Branch**: \`${context.payload.pull_request.head.ref}\`
              **Commit**: \`${context.payload.pull_request.head.sha.substring(0, 7)}\`
              
              The preview will be available for 30 days.`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: comment,
              });
            }