name: CI (testing)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  shared:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install shared (editable)
        working-directory: shared
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .[dev]
          ruff check .
          black --check .
          mypy shared
          pytest -q

  testing_app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: forge
          POSTGRES_PASSWORD: forge
          POSTGRES_DB: forge1_testing
        ports:
          - 5542:5432
        options: >-
          --health-cmd="pg_isready -U forge" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7-alpine
        ports:
          - 6380:6379
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        working-directory: testing-app
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ../shared
      - name: Lint/Type/Tests
        working-directory: testing-app
        env:
          DATABASE_URL: postgresql+psycopg://forge:forge@localhost:5542/forge1_testing
          REDIS_URL: redis://localhost:6380/1
        run: |
          source .venv/bin/activate
          ruff check .
          black --check .
          mypy app
          pytest -q


