name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: forge
          POSTGRES_PASSWORD: forge
          POSTGRES_DB: forge
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U forge" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        working-directory: backend
        run: |
          pip install ruff mypy black
          ruff check .
          mypy app
          black --check .
      - name: Smoke test API startup
        working-directory: backend
        env:
          DATABASE_URL: postgresql://forge:forge@localhost:5432/forge
          REDIS_URL: redis://localhost:6379/0
          BACKEND_CORS_ORIGINS: '*'
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl -f http://localhost:8000/api/v1/health || (cat nohup.out; exit 1)


