name: Release forge1-admin (optional)

on:
  workflow_dispatch:
  push:
    tags:
      - 'cli-v*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tools
        run: pip install build twine
      - name: Build wheel
        working-directory: cli/forge1_admin
        run: python -m build
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/cli-v')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        working-directory: cli/forge1_admin
        run: python -m twine upload dist/*

