name: Release SDKs

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish-sdks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install openapi-generator
        run: npm i -g @openapitools/openapi-generator-cli
      - name: Build SDKs
        run: |
          chmod +x scripts/sdk/gen_sdks.sh
          API_URL=${{ secrets.FORGE1_OPENAPI_URL }} ./scripts/sdk/gen_sdks.sh
      - name: Publish TS SDK
        if: ${{ secrets.NPM_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd sdks/typescript
          npm version from-git --no-git-tag-version || true
          npm publish --provenance --access public
      - name: Publish Python SDK
        if: ${{ secrets.PYPI_TOKEN != '' }}
        run: |
          python -m pip install --upgrade build twine
          cd sdks/python
          python -m build
          python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*


