name: Deploy Client Portal to Azure Static Web Apps (Staging)

on:
  push:
    branches: [ staging, main ]
    paths:
      - "frontend/**"
      - ".github/workflows/swa-deploy.yml"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_BASE_URL: https://forge1-backend-v2.agreeablebush-fb7c993c.eastus.azurecontainerapps.io
      NEXT_PUBLIC_ENV_LABEL: Staging
      NEXT_PUBLIC_GIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build & Deploy to Azure Static Web Apps (SSR aware)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: ""
          output_location: ".next"
          app_build_command: |
            echo "NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL" >> .env.production
            echo "NEXT_PUBLIC_ENV_LABEL=$NEXT_PUBLIC_ENV_LABEL" >> .env.production
            echo "NEXT_PUBLIC_GIT_SHA=$NEXT_PUBLIC_GIT_SHA" >> .env.production
            npm run build


